---
name: Test
on:
  push:
    branches:
      - "*"
      - "!releases/**"
    paths:
      - "docs/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker run -v $(pwd):/docs --entrypoint mkdocs squidfunk/mkdocs-material:6.1.5 build --clean --strict --site-dir /tmp/mkdocs-test
